// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $countdown from "./routes/countdown.tsx";
import * as $index from "./routes/index.tsx";
import * as $nhk_connect_index from "./routes/nhk-connect/index.tsx";
import * as $nhk_connect_nhkapi from "./routes/nhk-connect/nhkapi.tsx";
import * as $nhk_connect_notification from "./routes/nhk-connect/notification.tsx";
import * as $nhk_connect_program from "./routes/nhk-connect/program.tsx";
import * as $search from "./routes/search.tsx";
import * as $Countdown from "./islands/Countdown.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Input from "./islands/Input.tsx";
import * as $Select from "./islands/Select.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/countdown.tsx": $countdown,
    "./routes/index.tsx": $index,
    "./routes/nhk-connect/index.tsx": $nhk_connect_index,
    "./routes/nhk-connect/nhkapi.tsx": $nhk_connect_nhkapi,
    "./routes/nhk-connect/notification.tsx": $nhk_connect_notification,
    "./routes/nhk-connect/program.tsx": $nhk_connect_program,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/Countdown.tsx": $Countdown,
    "./islands/Counter.tsx": $Counter,
    "./islands/Input.tsx": $Input,
    "./islands/Select.tsx": $Select,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
